_BASE_: ../Base-AGW.yml

MODEL:
  BACKBONE:
    NAME: build_resnest_backbone
  WEIGHTS: '/home/lorenzo/PycharmProjects/ReID/fast-reid/logs/CMDM/agw_S50/model_best.pth'
  TEST_WEIGHTS: '/home/lorenzo/PycharmProjects/ReID/fast-reid/logs/market1501/agw_S50/model_best.pth'

DATASETS:
  NAMES: ("Market1501",)
  TESTS: ("Market1501",)

OUTPUT_DIR: logs/market1501/agw_S50
