_BASE_: ../Base-AGW.yml

MODEL:
  BACKBONE:
    PRETRAIN: False
  WEIGHTS: './logs/CMDM/agw_R50/model_best.pth'
  TEST_WEIGHTS: './logs/market1501/agw_R50/model_best.pth'

SOLVER:
  AMP:
    ENABLED: False

DATASETS:
  NAMES: ("Market1501",)
  TESTS: ("Market1501",)

#TEST:
#  METRIC: 'cosine'

OUTPUT_DIR: logs/market1501/agw_R50
