_BASE_: ../Base-AGW.yml

MODEL:
  BACKBONE:
    PRETRAIN: False
  WEIGHTS: './logs/CMDM/agw_R50/model_best.pth'
  TEST_WEIGHTS: './logs/market1501/agw_R50/model_best.pth'  # market1501

SOLVER:
  AMP:
    ENABLED: False
  # MAX_EPOCH: 10
  # BASE_LR: 0.00035
  # STEPS: [10, 20]

  # WARMUP_ITERS: 0
  # CHECKPOINT_PERIOD: 2

DATASETS:
  NAMES: ("Market1501",)
  TESTS: ("Market1501",)

#TEST:
#  METRIC: 'cosine'
OUTPUT_DIR: logs/market1501/agw_R50_pruning2
PRUNING: True
