_BASE_: ../Base-bagtricks.yml
# replace GlobalAveragePooling with GeneralizedMeanPooling

MODEL:
  PRETRAIN: True
  PRETRAIN_PATH: logs/CMDM/bagtricks_R50-8/model_best.pth

  HEADS:
    POOL_LAYER: GeneralizedMeanPooling

DATASETS:
  NAMES: ("Market1501", )
  TESTS: ("Market1501", )
# TEST:
#   EVAL_PERIOD: 1

OUTPUT_DIR: ./logs/market1501/bagtricks_R50-9

#SOLVER:
#  IMS_PER_BATCH: 400