_BASE_: ../Base-bagtricks.yml
# fast-reid settings

MODEL:
  PRETRAIN: False

  BACKBONE:
    DEPTH: "101x"
    PRETRAIN: True
    WITH_NL: True
    WITH_IBN: True
    # WITH_SE: True

  HEADS:
    POOL_LAYER: GeneralizedMeanPoolingP

  FREEZE_LAYERS: [ backbone ]

  LOSSES:
    NAME: ("CrossEntropyLoss", "TripletLoss", "CircleLoss") # ("TripletLoss", "CircleLoss")

    TRI:
      MARGIN: 0.3
      HARD_MINING: True
      NORM_FEAT: False
      SCALE: 1.

    CIRCLE:
      SCALE: 0.1


SOLVER:
  MAX_EPOCH: 90

  SCHED: CosineAnnealingLR
  ETA_MIN_LR: 7.7e-7

  FREEZE_ITERS: 2000

  DELAY_EPOCHS: 35
  WARMUP_FACTOR: 0.01

INPUT:
  SIZE_TRAIN: [ 384, 128 ]
  SIZE_TEST: [ 384, 128 ]

  AUTOAUG:
    ENABLED: True
    PROB: 0.1

DATASETS:
  NAMES: ("Market1501",)
  TESTS: ("Market1501",)

# TEST:
#   EVAL_PERIOD: 1

OUTPUT_DIR: logs/market1501/bagtricks_R101-11
