_BASE_: ../Base-bagtricks.yml

MODEL:
  PRETRAIN: True
  PRETRAIN_PATH: logs/CMDM/bagtricks_M2-11/model_best.pth
  BACKBONE:
    NAME: build_mobilenetv2_backbone
    DEPTH: 1.0x
    FEAT_DIM: 1280
    # PRETRAIN: True
    # PRETRAIN_PATH: /home/vitis-ai-user/.cache/torch/checkpoints/mobilenet_v2.pth.tar

DATASETS:
  NAMES: ("Market1501",)
  TESTS: ("Market1501",)

OUTPUT_DIR: logs/market1501/bagtricks_M2-12
