_BASE_: ../Base-AGW.yml

MODEL:
  BACKBONE:
    PRETRAIN: True
    PRETRAIN_PATH: "/home/lorenzo/.cache/torch/checkpoints/resnet50-19c8e357.pth"

DATASETS:
  NAMES: ("Market1501", "CUHK03", "DukeMTMC", "MSMT17")
  TESTS: ("Market1501", "CUHK03", "DukeMTMC", "MSMT17")

OUTPUT_DIR: logs/CMDM/agw_R50

#SOLVER:
#  IMS_PER_BATCH: 384