_BASE_: ../Base-bagtricks.yml

MODEL:
  BACKBONE:
    PRETRAIN: False
    WITH_SE: True

DATASETS:
  NAMES: ("Market1501", "CUHK03", "DukeMTMC", "MSMT17")
  TESTS: ("Market1501", "CUHK03", "DukeMTMC", "MSMT17")

OUTPUT_DIR: logs/CMDM/bagtricks_R50-se 
