_BASE_: ../Base-bagtricks.yml

MODEL:
  PRETRAIN: True
  PRETRAIN_PATH: logs/CMDM/bagtricks_S50-10/model_best.pth
  BACKBONE:
    NAME: build_resnest_backbone
    PRETRAIN: False
    # PRETRAIN_PATH: '/home/lorenzo/.cache/torch/checkpoints/resnest50-528c19ca.pth'

DATASETS:
  NAMES: ("DukeMTMC", )
  TESTS: ("DukeMTMC", )

# TEST:
#   RERANK: 
#     ENABLED: True

OUTPUT_DIR: logs/dukemtmc/bagtricks_S50-10
