_BASE_: ../Base-SBS.yml

MODEL:
  BACKBONE:
    NAME: build_resnest_backbone
  # WEIGHTS: '/home/lorenzo/PycharmProjects/ReID/fast-reid/logs/CMDM/sbs_S50/model_best.pth'
  TEST_WEIGHTS: '/home/lorenzo/PycharmProjects/ReID/fast-reid/logs/dukemtmc/sbs_S50/model_best.pth'

DATASETS:
  NAMES: ("DukeMTMC",)
  TESTS: ("DukeMTMC",)

OUTPUT_DIR: logs/dukemtmc/sbs_S50
