_BASE_: ../Base-AGW.yml

MODEL:
  BACKBONE:
    PRETRAIN: False
  WEIGHTS: '/home/lorenzo/PycharmProjects/ReID/fast-reid/logs/CMDM/agw_R50/model_best.pth'

DATASETS:
  NAMES: ("CUHK03",)
  TESTS: ("CUHK03",)

OUTPUT_DIR: logs/cuhk03/agw_R50
