# encoding: utf-8
"""
@author:  lorenzo
@contact: baiyingpoi123@gmail.com
"""
import argparse
import os
import sys
import torch
import logging
from pytorch_nndct import get_pruning_runner
sys.path.append('.')
# sys.path.append('/workspace/lorenzo/ReID/lorenzo-reid-baseline')
from config.config import get_cfg
from playreid.engine.engine import do_test, default_setup
from playreid.modeling import build_model
from playreid.utils.checkpoint import Checkpointer


def default_argument_parser():
    """
    Create a parser with some common arguments used.
    Returns:
        argparse.ArgumentParser:
    """
    parser = argparse.ArgumentParser(description="Lorenzo ReID Baseline Training")
    parser.add_argument("-f", "--config-file", default="/workspace/lorenzo/ReID/lorenzo-reid-baseline/configs/Market1501/bagtricks_R50.yml", type=str, help="path to config file")
    parser.add_argument("-s", "--sparsity", type=float, default=0.5, help="sparsity ratio of model")
    parser.add_argument("opts", help="Modify config options using the command-line", default=None, nargs=argparse.REMAINDER)
    return parser

    
def setup(args):
    """
    Create configs and perform basic setups.
    """
    # This function loads default configuration written in ./config/default.py .
    cfg = get_cfg()
    # Merge configs from a given yaml file.
    cfg.merge_from_file(args.config_file)
    # Merge configs from list generated by args.opts
    cfg.merge_from_list(args.opts)  # ['MODEL.DEVICE', 'cuda:0']
    cfg.MODEL.PRETRAIN = False
    cfg.MODEL.BACKBONE.PRETRAIN = False
    cfg.OUTPUT_DIR = os.path.join(cfg.OUTPUT_DIR, 'iterative_prune', f'sparsity_{args.sparsity}')
    cfg.freeze()
    default_setup(cfg, args, 'log_compare.txt')
    return cfg


def main(args):
    cfg = setup(args)
    
    sparse_model_path = os.path.join(cfg.OUTPUT_DIR, f"model_sparsity_{args.sparsity}.pth")
    assert os.path.exists(sparse_model_path), "No sparse model!"
    slim_model_path = os.path.join(cfg.OUTPUT_DIR, f"model_slim_{args.sparsity}.pth")
    assert os.path.exists(slim_model_path), "No slim model!"

    sparse_model = build_model(cfg)
    Checkpointer(sparse_model).load(sparse_model_path)
    # print(sparse_model)

    input_signature = torch.randn([1, 3, 256, 128], dtype=torch.float32)
    input_signature = input_signature.to(torch.device(cfg.MODEL.DEVICE))
    pruning_runner = get_pruning_runner(sparse_model, input_signature, 'iterative')
    slim_model = pruning_runner.prune(removal_ratio=args.sparsity, mode='slim',
                                      excludes=[sparse_model.backbone.layer4[2].conv3,
                                                sparse_model.heads])
    Checkpointer(slim_model).load(slim_model_path)
    # print(slim_model)
    # exit(0)
    
    print("*"*100)
    print("This is sparse model!")
    do_test(cfg, sparse_model)

    print("*"*100)
    print("This is slim model!")
    do_test(cfg, slim_model)


if __name__ == "__main__":
    args = default_argument_parser().parse_args()
    print("Command Line Args:", args)
    main(args)