_BASE_: ../Base-AGW.yml

MODEL:
  BACKBONE:
    PRETRAIN: False
  WEIGHTS: '/home/lorenzo/PycharmProjects/ReID/fast-reid/logs/CMDM/agw_R50/model_best.pth'

DATASETS:
  NAMES: ("MSMT17",)
  TESTS: ("MSMT17",)

OUTPUT_DIR: logs/msmt17/agw_R50
